"""add_provider_to_system_prompts

Revision ID: 056460e4057e
Revises: a3261eb3087b
Create Date: 2026-04-27 17:22:18.064745
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "056460e4057e"
down_revision = "a3261eb3087b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "system_prompts",
        sa.Column("provider", sa.String(length=32), server_default="openai", nullable=False),
    )
    op.add_column(
        "system_prompts",
        sa.Column("model_id", sa.String(length=255), server_default="gpt-4o-mini", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("system_prompts", "model_id")
    op.drop_column("system_prompts", "provider")
    # ### end Alembic commands ###
