"""add_utterance_indexes

Revision ID: 0ae531a57aaa
Revises: 9228797f839a
Create Date: 2026-07-06 19:36:46.696863
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = '0ae531a57aaa'
down_revision = '9228797f839a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_utterances_conversation_id_timestamp', 'utterances', ['conversation_id', 'timestamp'], unique=False)
    op.create_index('ix_utterances_speaker_id_status', 'utterances', ['speaker_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_utterances_speaker_id_status', table_name='utterances')
    op.drop_index('ix_utterances_conversation_id_timestamp', table_name='utterances')
    # ### end Alembic commands ###
