"""add_daily_prompts

Revision ID: 1a04ffb9360b
Revises: 056460e4057e
Create Date: 2026-04-27 19:48:51.975444
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "1a04ffb9360b"
down_revision = "056460e4057e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_prompts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("day_identifier", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("day_identifier"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_prompts")
    # ### end Alembic commands ###
