"""Drop the leftover backfill default on speakers.created_at.

speakers was created without created_at (20260107_0001). When
7017c70683d8 added the column it had to populate existing rows, and a NOT NULL
column cannot be added to a populated table without one — so it was given
server_default=now(). In that same migration conversations and utterances got
created_at at CREATE TABLE time, where there are no rows to backfill, and so
carry no server default. speakers has been the odd one out ever since.

Base declares only a Python-side default, so the database and the model have
disagreed since January. Nothing noticed because autogenerate does not compare
server defaults until asked; 8dadf54491c8 turned compare_server_default on and
this surfaced immediately, and would have reappeared in every migration
generated from here on.

Dropping it is safe: every insert goes through get_or_create_speaker and the
ORM, which supplies created_at from the Python default. There are no raw
inserts into speakers.

Revision ID: 40705f296d71
Revises: 8dadf54491c8
Create Date: 2026-08-24 19:06:40.907244
"""
from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '40705f296d71'
down_revision = '8dadf54491c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('speakers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('speakers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###
