"""add_day_identifier_to_conversations

Revision ID: 56b8ef4d3a9c
Revises: 1a04ffb9360b
Create Date: 2026-04-27 20:10:22.186776
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "56b8ef4d3a9c"
down_revision = "1a04ffb9360b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("conversations", sa.Column("day_identifier", sa.Integer(), nullable=True))
    op.drop_index(
        op.f("ux_conversations_owner_open"),
        table_name="conversations",
        postgresql_where="((status)::text = 'open'::text)",
    )
    op.create_index(
        "ux_conversations_owner_open_day",
        "conversations",
        ["owner_speaker_id", "day_identifier"],
        unique=True,
        postgresql_where=sa.text("status = 'open' AND day_identifier IS NOT NULL"),
    )
    op.create_index(
        "ux_conversations_owner_open_no_day",
        "conversations",
        ["owner_speaker_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open' AND day_identifier IS NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ux_conversations_owner_open_no_day",
        table_name="conversations",
        postgresql_where=sa.text("status = 'open' AND day_identifier IS NULL"),
    )
    op.drop_index(
        "ux_conversations_owner_open_day",
        table_name="conversations",
        postgresql_where=sa.text("status = 'open' AND day_identifier IS NOT NULL"),
    )
    op.create_index(
        op.f("ux_conversations_owner_open"),
        "conversations",
        ["owner_speaker_id"],
        unique=True,
        postgresql_where="((status)::text = 'open'::text)",
    )
    op.drop_column("conversations", "day_identifier")
    # ### end Alembic commands ###
