"""add instruction templates

Revision ID: 5c06f3ce5e65
Revises: ac1db7fe40e2
Create Date: 2026-07-27 13:24:42.417375
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "5c06f3ce5e65"
down_revision = "ac1db7fe40e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instruction_templates",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("template", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("instruction_templates")
    # ### end Alembic commands ###
