"""add_open_conversation_unique_index

Revision ID: 654869edb0b0
Revises: 7017c70683d8
Create Date: 2026-01-07 12:03:06.773662
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = '654869edb0b0'
down_revision = '7017c70683d8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ux_conversations_owner_open",
        "conversations",
        ["owner_speaker_id"],
        unique=True,
        postgresql_where=sa.text("status = 'open'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ux_conversations_owner_open",
        table_name="conversations",
        postgresql_where=sa.text("status = 'open'"),
    )
    # ### end Alembic commands ###
