"""add_system_prompts

Revision ID: 86eff0152bb6
Revises: e5dbd3a937d3
Create Date: 2026-02-20 14:05:21.138101
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "86eff0152bb6"
down_revision = "e5dbd3a937d3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "system_prompts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("system_prompts")
    # ### end Alembic commands ###
