"""add moderation_settings

Revision ID: 89d36122d523
Revises: 40705f296d71
Create Date: 2026-09-16 18:37:57.902097
"""

from __future__ import annotations

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "89d36122d523"
down_revision = "40705f296d71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "moderation_settings",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("email_enabled", sa.Boolean(), nullable=False),
        sa.Column("thresholds", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("id = 1", name="ck_moderation_settings_singleton"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("moderation_settings")
    # ### end Alembic commands ###
