"""default_system_prompt_model_to_bedrock_llama

Revision ID: 8dadf54491c8
Revises: 9796c9e491df
Create Date: 2026-08-24 17:55:00.551715
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = '8dadf54491c8'
down_revision = '9796c9e491df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_prompts', 'provider',
               existing_type=sa.VARCHAR(length=32),
               server_default='bedrock',
               existing_nullable=False)
    op.alter_column('system_prompts', 'model_id',
               existing_type=sa.VARCHAR(length=255),
               server_default='us.meta.llama4-maverick-17b-instruct-v1:0',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_prompts', 'model_id',
               existing_type=sa.VARCHAR(length=255),
               server_default=sa.text("'gpt-4o-mini'::character varying"),
               existing_nullable=False)
    op.alter_column('system_prompts', 'provider',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'openai'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
