"""add prompt issues and failed reply index

Revision ID: 9796c9e491df
Revises: 5c06f3ce5e65
Create Date: 2026-07-27 20:08:59.397640
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "9796c9e491df"
down_revision = "5c06f3ce5e65"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prompt_issues",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("utterance_id", sa.String(length=32), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_prompt_issues_created_at", "prompt_issues", ["created_at"], unique=False)
    op.create_index(
        "ix_utterances_failed_timestamp",
        "utterances",
        ["timestamp"],
        unique=False,
        postgresql_where=sa.text("status = 'failed'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_utterances_failed_timestamp",
        table_name="utterances",
        postgresql_where=sa.text("status = 'failed'"),
    )
    op.drop_index("ix_prompt_issues_created_at", table_name="prompt_issues")
    op.drop_table("prompt_issues")
    # ### end Alembic commands ###
