"""add_utterance_moderated_status

Revision ID: 9fcf9a304b58
Revises: 86eff0152bb6
Create Date: 2026-04-03 12:37:38.825375
"""

from __future__ import annotations

from alembic import op

revision = "9fcf9a304b58"
down_revision = "86eff0152bb6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_utterances_status", "utterances", type_="check")
    op.create_check_constraint(
        "ck_utterances_status",
        "utterances",
        "status in ('received', 'queued', 'sent', 'moderated', 'failed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_utterances_status", "utterances", type_="check")
    op.create_check_constraint(
        "ck_utterances_status",
        "utterances",
        "status in ('received', 'queued', 'sent', 'failed')",
    )
    # ### end Alembic commands ###
