"""add_weekly_summaries

Revision ID: a3261eb3087b
Revises: 9fcf9a304b58
Create Date: 2026-04-17 15:49:22.613804
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "a3261eb3087b"
down_revision = "9fcf9a304b58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weekly_summaries",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("week_start", sa.Date(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["speakers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "week_start", name="uq_weekly_summaries_user_week"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weekly_summaries")
    # ### end Alembic commands ###
