"""add_reply_queue_claim_columns

Revision ID: a82e79c02377
Revises: 0ae531a57aaa
Create Date: 2026-07-07 01:16:20.051261
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'a82e79c02377'
down_revision = '0ae531a57aaa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utterances', sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('utterances', sa.Column('attempts', sa.Integer(), server_default='0', nullable=False))
    op.create_index('ix_utterances_pending_timestamp', 'utterances', ['status', 'timestamp'], unique=False, postgresql_where=sa.text("status in ('queued', 'processing')"))
    op.drop_constraint('ck_utterances_status', 'utterances', type_='check')
    op.create_check_constraint(
        'ck_utterances_status',
        'utterances',
        "status in ('received', 'queued', 'processing', 'sent', 'moderated', 'failed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_utterances_status', 'utterances', type_='check')
    op.create_check_constraint(
        'ck_utterances_status',
        'utterances',
        "status in ('received', 'queued', 'sent', 'moderated', 'failed')",
    )
    op.drop_index('ix_utterances_pending_timestamp', table_name='utterances', postgresql_where=sa.text("status in ('queued', 'processing')"))
    op.drop_column('utterances', 'attempts')
    op.drop_column('utterances', 'claimed_at')
    # ### end Alembic commands ###
