"""add summarization prompts

Revision ID: ac1db7fe40e2
Revises: a82e79c02377
Create Date: 2026-07-27 13:07:06.376529
"""

from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = "ac1db7fe40e2"
down_revision = "a82e79c02377"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "summarization_prompts",
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("summarization_prompts")
    # ### end Alembic commands ###
