"""add_utterance_status

Revision ID: d24f6d70fabd
Revises: 654869edb0b0
Create Date: 2026-01-16 11:30:09.714869
"""
from __future__ import annotations

import sqlalchemy as sa

from alembic import op

revision = 'd24f6d70fabd'
down_revision = '654869edb0b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'utterances',
        sa.Column(
            'status',
            sa.String(length=16),
            nullable=False,
            server_default=sa.text("'received'"),
        ),
    )
    op.add_column('utterances', sa.Column('error', sa.Text(), nullable=True))
    op.alter_column('utterances', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    op.execute(
        "UPDATE utterances "
        "SET status = CASE "
        "WHEN speaker_id LIKE 'bot:%' THEN 'sent' "
        "ELSE 'received' "
        "END"
    )
    op.alter_column('utterances', 'status', server_default=None)
    op.create_check_constraint(
        'ck_utterances_status',
        'utterances',
        "status in ('received', 'queued', 'sent', 'failed')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_utterances_status', 'utterances', type_='check')
    op.execute("UPDATE utterances SET text = '' WHERE text IS NULL")
    op.alter_column('utterances', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('utterances', 'error')
    op.drop_column('utterances', 'status')
    # ### end Alembic commands ###
