"""rename_day_identifier_to_day_number

Revision ID: d740e0090bdc
Revises: 56b8ef4d3a9c
Create Date: 2026-05-21 17:56:04.801839
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



revision = 'd740e0090bdc'
down_revision = '56b8ef4d3a9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('day_number', sa.Integer(), nullable=True))
    op.drop_index(op.f('ux_conversations_owner_open_day'), table_name='conversations', postgresql_where="(((status)::text = 'open'::text) AND (day_identifier IS NOT NULL))")
    op.create_index('ux_conversations_owner_open_day', 'conversations', ['owner_speaker_id', 'day_number'], unique=True, postgresql_where=sa.text("status = 'open' AND day_number IS NOT NULL"))
    op.drop_column('conversations', 'day_identifier')
    op.add_column('daily_prompts', sa.Column('day_number', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('daily_prompts_day_identifier_key'), 'daily_prompts', type_='unique')
    op.create_unique_constraint(None, 'daily_prompts', ['day_number'])
    op.drop_column('daily_prompts', 'day_identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('daily_prompts', sa.Column('day_identifier', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'daily_prompts', type_='unique')
    op.create_unique_constraint(op.f('daily_prompts_day_identifier_key'), 'daily_prompts', ['day_identifier'], postgresql_nulls_not_distinct=False)
    op.drop_column('daily_prompts', 'day_number')
    op.add_column('conversations', sa.Column('day_identifier', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index('ux_conversations_owner_open_day', table_name='conversations', postgresql_where=sa.text("status = 'open' AND day_number IS NOT NULL"))
    op.create_index(op.f('ux_conversations_owner_open_day'), 'conversations', ['owner_speaker_id', 'day_identifier'], unique=True, postgresql_where="(((status)::text = 'open'::text) AND (day_identifier IS NOT NULL))")
    op.drop_column('conversations', 'day_number')
    # ### end Alembic commands ###
