UTTERANCE_STATUS_RECEIVED = "received"
UTTERANCE_STATUS_QUEUED = "queued"
UTTERANCE_STATUS_SENT = "sent"
UTTERANCE_STATUS_FAILED = "failed"

UTTERANCE_STATUSES = (
    UTTERANCE_STATUS_RECEIVED,
    UTTERANCE_STATUS_QUEUED,
    UTTERANCE_STATUS_SENT,
    UTTERANCE_STATUS_FAILED,
)

UTTERANCE_STATUSES_SQL = ", ".join(f"'{status}'" for status in UTTERANCE_STATUSES)
